config/routes.rb
PartyManager::Application.routes.draw do
  root :to => 'home#index'
  
  match 'index' => 'home#index', :as => :index

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'host/edit' => 'hosts#edit', :as => :edit_current_host

  match 'signup' => 'hosts#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'rsvp/:invite_code', :via => :get , :to => 'invitations#rsvp', :as => 'rsvp'
  
  match 'thanks', :to => 'invitations#thanks', :as => 'thanks'

  resources :sessions

  resources :hosts

  resources :gifts

  resources :invitations

  resources :parties

  resources :guests

  resources :locations

end

app/models/party.rb
class Party < ActiveRecord::Base
	belongs_to :host
	belongs_to :location
	belongs_to :party_type
	has_many :invitations, :dependent => :destroy
	has_many :guests, :through => :invitations
	
	scope :all, order(:name.asc)
    scope :upcoming, where(:date > Date.yesterday).order(:date.asc)
    scope :past,     where(:date <= Date.yesterday).order(:date.desc)
	scope :desc, order(:date.desc)
	
	#validates :date, :presence => true, :date => {:after => Proc.new { Date.yesterday } }
	validates :name, :presence => true
	validates :date, :presence => true, :timeliness => { :type => :date}
	validates :rsvp_date, :timeliness => { :allow_nil => true, :on_or_before => :date, :type => :date }
	validates :start_time, :presence => true
	validates :end_time, :presence => true, :timeliness => { :after => :start_time, :type => :time }
	
	def number_expected_guests
		return self.guests.sum('expected_attendees')
	end
	
	def number_actual_guests
		return self.guests.sum('actual_attendees')
	end
end

app/models/party_type.rb
class PartyType < ActiveRecord::Base
	has_many :parties, :dependent => :nullify
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :login_required
  # GET /parties
  # GET /parties.xml
  def index
    @upcoming_parties = current_host.parties.upcoming
	@past_parties = current_host.parties.past
  end

  # GET /parties/1
  # GET /parties/1.xml
  def show
    @party = Party.find(params[:id])
	@invitations = @party.invitations.all
  end

  # GET /parties/new
  # GET /parties/new.xml
  def new
    @party = Party.new
	@locations = current_host.locations

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
	@locations = current_host.locations
  end

  # POST /parties
  # POST /parties.xml
  def create
    params[:party][:host_id] = current_host.id
	@locations = current_host.locations

    @party = Party.new(params[:party])
	if params[:new_location_name] != "" && params[:new_location_address] != ""
		l = Location.new( :name => params[:new_location_name], :address => params[:new_location_address] )
		l.host_id = current_host.id
		l.save!
		@party.location_id = l.id
	end
    respond_to do |format|
      if @party.save
        format.html { redirect_to(@party, :notice => 'Party was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.xml
  def update
    @party = Party.find(params[:id])
	params[:party][:host_id] = current_host.id
	@locations = current_host.locations
	
	if params[:new_location_name] != "" && params[:new_location_address] !=""
		l = Location.new( :name => params[:new_location_name], :address => params[:new_location_address] )
		l.host_id = current_host.id
		l.save!
		params[:party][:location_id] = l.id
	end

	
    respond_to do |format|
      if @party.update_attributes(params[:party])
		@party.invitations.each do |i|
			PartyMailer.party_update(i).deliver
		end
        format.html { redirect_to(@party, :notice => 'Party was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.xml
  def destroy
    @party = Party.find(params[:id])
	@party.invitations.each do |i|
		PartyMailer.party_delete(i).deliver
	end
    @party.destroy

    respond_to do |format|
      format.html { redirect_to(parties_url, :notice => 'Party was successfully deleted and all guests notified.') }
    end
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <%= render :partial => "partials/errors", :locals => {:target => @party}  %>

  <div class="field">
    <%= f.label :name, 'Name: <span class="required">*</span>'.html_safe %> 
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date, 'Date: <span class="required">*</span>'.html_safe %> 
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :location_id, "Choose existing location:" %> 
    <%= f.collection_select(:location_id ,@locations,:id, :name,{:include_blank =>"Select Location"}) %>
  </div>
  <div class="field">
	<%= label_tag :new_location_name, "Location Name:" %>
	<%= text_field_tag :new_location_name, params[:new_location_name] %>
  </div>
  <div class="field">
	<%= label_tag :new_location_address, "Address:" %>
	<%= text_field_tag :new_location_address, params[:new_location_address] %>
  </div>
  <div class="field">
	<%= f.label :start_time, 'Start Time: <span class="required">*</span>'.html_safe %> 
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
	<%= f.label :end_time, 'End Time: <span class="required">*</span>'.html_safe %> 
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :description %> 
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rsvp_date %> 
    <%= f.date_select :rsvp_date %>
  </div>
  <p>Checking public guestlist will allow RSVPing guests to see the guestlist.</p>
  <div class="field">
    <%= f.label :public_guestlist %> 
    <%= f.check_box :public_guestlist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/_party_guest_list.html.erb
<h2 class="horizontal slide">Guest List</h2>
<% if invitations.length > 0 %>
  <table class="minimal">
  	<thead>
  		<tr>
  			<th>Name</th>
  			<th>Email</th>
			<th>Invite Sent</th>
  			<th># Expected</th>
  			<th># RSVP</th>
			<th>Actions</th>
  		</tr>
  	</thead>
  	<tbody>
  		<% for invite in invitations %>
    	<tr>
    		<td><%= link_to invite.guest.name , guest_path(invite.guest) %> </td>
    		<td><%= invite.guest.email %></td>
			<td><%= date_str invite.created_at %></td>
    		<td><%= invite.expected_attendees %></td>
    		<td><%= invite.actual_attendees %>  </td>
			<td><%= link_to 'Show Invitation', invite %></td>
    	</tr>
  		<% end%>
  	</tbody>
  </table>
<% end%>

app/views/parties/_party_show.html.erb
<% if party.location && party.location.longitude %>
	<%= render :partial => "partials/gmap", :locals => {:latitude => party.location.latitude,:longitude => 
												party.location.longitude }%> 
<% end %>

<% if show_party_name %>
	<h1 class="horizontal"><%= party.name %></h1>
<% end %>
<div id="party_details_map">
	<div id="party_detail_container">
		<table class="details">
			<tr>
				<td>Date & Time:</td>
				<td><%= date_str party.date %> &nbsp <%= time_str party.start_time %> - <%= time_str party.end_time %></td>
			</tr>
			<% if party.location %>
			<tr>
				<td>Location:</td>
				<td><%= party.location.name %> - <a id="address_link" href="#"><%= party.location.address %> <span id="google_maps_icon" </span></a></td>
			</tr>
			<div id="map_canvas" class="party_show">
			</div>
			<% end %>
			<% if party.description != "" %>
			<tr>
				<td>Description:</td>
				<td><%= party.description %></td>
			</tr>
			<% end %>
			<tr>
				<td>RSVP Date:</td>
				<td><%= date_str party.rsvp_date %></td>
			</tr>
		</table>
	</div>
	
</div>

app/views/parties/edit.html.erb
<h1 class="horizontal">Editing <%= @party.name %></h1>

<%= render 'form' %>

<div class="link_actions">
<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>
</div>

app/views/parties/index.html.erb
<% if @upcoming_parties.length > 0 || @past_parties.length > 0 %>
	<% if @upcoming_parties.length > 0 %>

	<h2 class="horizontal">Upcoming Parties</h2>

	<table class="minimal">
	  <tr>
		<th>Name</th>
		<th>Date</th>
		<th>Location</th>
		<th>Time</th>
		<th># Expected</th>
		<th># Confirmed</th>
	  </tr>

	<% @upcoming_parties.each do |party| %>
	  <tr>
		<td><%= link_to party.name, party %></td>
		<td><%= date_str party.date %></td>
		<td><%= party.location.name if party.location %></td>
		<td><%= "#{time_str party.start_time} - #{time_str party.end_time}" %></td>
		<td><%= party.number_expected_guests %></td>
		<td><%= party.number_actual_guests %></td>
	  </tr>
	<% end %>
	</table>
	<% end %>
	<% if @past_parties.length > 0 %>
	<h2 class="horizontal">Past Parties</h2>

	<table class="minimal">
	  <tr>
		<th>Name</th>
		<th>Date</th>
		<th>Location</th>
		<th>Time</th>
		<th># Expected</th>
		<th># Confirmed</th>
	  </tr>

	<% @past_parties.each do |party| %>
	  <tr>
		<td><%= link_to party.name, party %></td>
		<td><%= date_str party.date %></td>
		<td><%= party.location.name if party.location  %></td>
		<td><%= "#{time_str party.start_time} - #{time_str party.end_time}" %></td>
		<td><%= party.number_expected_guests %></td>
		<td><%= party.number_actual_guests %></td>
	  </tr>
	<% end %>
	</table>
	<% end %>
<% else %>
	<h2 class="horizontal">No Parties to display</h2>
	<p>You have no parties to display. Get started by creating a party!</p>
<% end %>
<br />

<div class="link_actions">
<%= link_to 'New Party', new_party_path %>
</div>
</div>

app/views/parties/new.html.erb
<h1 class="horizontal">New party</h1>

<%= render 'form' %>

<div class="link_actions">
<%= link_to 'Back', parties_path %>
</div>

app/views/parties/show.html.erb
<%= render :partial => 'party_show', :locals => {:party => @party, :show_party_name => true} %>
<%= render :partial => 'party_guest_list', :locals => {:invitations => @invitations} %>

<div class="link_actions">
<%= link_to 'Back', parties_path %> |
<%= link_to "Edit", edit_party_path(@party) %> |
<%= link_to "Destroy", @party, :confirm => 'Are you sure?', :method => :delete %>
</div>