config/routes.rb
PartyManager::Application.routes.draw do
  root :to => 'home#index'
  
  match 'index' => 'home#index', :as => :index

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'host/edit' => 'hosts#edit', :as => :edit_current_host

  match 'signup' => 'hosts#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'rsvp/:invite_code', :via => :get , :to => 'invitations#rsvp', :as => 'rsvp'
  
  match 'thanks', :to => 'invitations#thanks', :as => 'thanks'

  resources :sessions

  resources :hosts

  resources :gifts

  resources :invitations

  resources :parties

  resources :guests

  resources :locations

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	belongs_to :host
	has_many :invitations, :dependent => :destroy
	has_many :parties, :through => :invitations
	
	scope :all, order(:name.asc)
	
	validates :name, :presence => true
	validates :email, :presence => true, :format => {:with => /^([0-9a-zA-Z]([-\.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})$/ , :message => "is not a valid format" }
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :login_required
  # GET /guests
  # GET /guests.xml
  def index
    @guests = current_host.guests.all
  end

  # GET /guests/1
  # GET /guests/1.xml
  def show
    @guest = Guest.find(params[:id])
	@invitations = @guest.invitations
  end

  # GET /guests/new
  # GET /guests/new.xml
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  # POST /guests.xml
  def create
    params[:guest][:host_id] = current_host.id
    @guest = Guest.new(params[:guest])

    respond_to do |format|
      if @guest.save
        format.html { redirect_to(@guest, :notice => 'Guest was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.xml
  def update
    @guest = Guest.find(params[:id])
	@guest.host_id = current_host.id

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to(@guest, :notice => 'Guest was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.xml
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to(guests_url) }
    end
  end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <%= render :partial => "partials/errors", :locals => {:target => @guest}  %>

  <div class="field">
	<%= f.label :name, 'Name: <span class="required">*</span>'.html_safe %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email , 'Email: <span class="required">*</span>'.html_safe%> 
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :notes %> 
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/guests/edit.html.erb
<h1 class="horizontal">Editing guest</h1>

<%= render 'form' %>

<div class="link_actions">
<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>
</div>

app/views/guests/index.html.erb
<% if @guests.length > 0 %>
	<h1 class="horizontal">Your Guests</h1>

	<table class="minimal">
	  <tr>
		<th>Name</th>
		<th>Email</th>
		<th>Notes</th>
		<th colspan="3">Actions</th>
	  </tr>

	<% @guests.each do |guest| %>
	  <tr>
		<td><%= guest.name %></td>
		<td><%= guest.email %></td>
		<td><%= guest.notes %></td>
		<td><%= link_to 'Show', guest %></td>
		<td><%= link_to 'Edit', edit_guest_path(guest) %></td>
		<td><%= link_to 'Destroy', guest, :confirm => 'Are you sure?', :method => :delete, :class => "fade" %></td>
	  </tr>
	<% end %>
	</table>
<% else %>
	<h2 class="horizontal">No Guests to display</h2>
	<p>You have no guests to display. Get started by creating some guests!</p>
<% end %>

<div class="link_actions">
<%= link_to 'New Guest', new_guest_path %>
</div>

app/views/guests/new.html.erb
<h1 class="horizontal">New guest</h1>

<%= render 'form' %>

<div class="link_actions">
<%= link_to 'Back', guests_path %>
</div>

app/views/guests/show.html.erb
<h1 class="horizontal">Guest: <%= @guest.name %></h1>

<p>
  <b>Email:</b>
  <%= @guest.email %>
</p>

<% if @guest.notes.nil? %>
<p>
  <b>Notes:</b>
  <%= @guest.notes %>
</p>
<% end %>
<% if @guest.parties.length > 0 %>
<h2 class="horizontal">Parties Attended</h2>
<table class="minimal">
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>Time</th>
	<th># Expected</th>
	<th># Confirmed</th>
  </tr>

<% @invitations.each do |invite| %>
  <tr>
    <td><%= link_to invite.party.name, invite.party %></td>
    <td><%= date_str invite.party.date %></td>
    <td><%= invite.party.location.name if invite.party.location %></td>
    <td><%= "#{time_str invite.party.start_time} - #{time_str invite.party.end_time}" %></td>
	<td><%= invite.expected_attendees %></td>
	<td><%= invite.actual_attendees %></td>
  </tr>
<% end %>
</table>
<% end %>

<div class="link_actions">
<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>
</div>