config/routes.rb
PartyManager::Application.routes.draw do
  root :to => 'home#index'
  
  match 'index' => 'home#index', :as => :index

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'host/edit' => 'hosts#edit', :as => :edit_current_host

  match 'signup' => 'hosts#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'rsvp/:invite_code', :via => :get , :to => 'invitations#rsvp', :as => 'rsvp'
  
  match 'thanks', :to => 'invitations#thanks', :as => 'thanks'

  resources :sessions

  resources :hosts

  resources :gifts

  resources :invitations

  resources :parties

  resources :guests

  resources :locations

end

app/views/partials/_errors.html.erb
<% if target.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/partials/_footer.html.erb
<div id="footer_container">
	<div id="footer">
		<span>Designed by: <%= mail_to "cjreyes@andrew.cmu.edu","Christian Reyes" %></span>
	</div>
</div>

app/views/partials/_gmap.html.erb
<% content_for :head do %>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true" %>
	<%= javascript_tag do %>
		var map;
		function create_map() {
			var latlng = new google.maps.LatLng(<%= latitude %>,<%= longitude %>);
			var myOptions = {
				zoom: 14,
				center: latlng,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
			marker = new google.maps.Marker({
				map:map,
				draggable:false,
				animation: google.maps.Animation.DROP,
				position: latlng
			});
		}
	<% end %>
<% end %>

app/views/partials/_header.html.erb
<div id="header">
	<div id="header_container">
		<a href="/"><h1>Party Manager</h1></a>
		<span>
		<% if logged_in? %>
			<% if administrator?%>
				Admin: 
			<% end %>
			<%= link_to current_host.name, edit_current_host_path(current_host) %> | 
			<%= link_to "Log out", logout_path %> 
		<% else %>
			<%= link_to "Sign up", signup_path %> or
			<%= link_to "log in", login_path %>.
		<% end %>
		</span>
	</div>
</div>

app/views/partials/_menu_bar.html.erb
<% if logged_in? %>
<div id="menu_container">
	<div id="menu">
		<ul>
			<li><%= link_to 'Parties', parties_path %></li>
			<li><%= link_to 'Guests', guests_path %></li>
			<li><%= link_to 'Invitations', invitations_path %></li>
			<li><%= link_to 'Locations', locations_path %></li>
			<li><%= link_to 'Gifts', gifts_path %></li>
		</ul>
	</div>
</div>
<% end %>