config/routes.rb
PartyManager::Application.routes.draw do
  root :to => 'home#index'
  
  match 'index' => 'home#index', :as => :index

  match 'about' => 'home#about', :as => :about

  match 'contact' => 'home#contact', :as => :contact

  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'host/edit' => 'hosts#edit', :as => :edit_current_host

  match 'signup' => 'hosts#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'rsvp/:invite_code', :via => :get , :to => 'invitations#rsvp', :as => 'rsvp'
  
  match 'thanks', :to => 'invitations#thanks', :as => 'thanks'

  resources :sessions

  resources :hosts

  resources :gifts

  resources :invitations

  resources :parties

  resources :guests

  resources :locations

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :party
	belongs_to :guest
	has_many :gifts, :dependent => :destroy
	
	before_create :generate_invite_code
	
	scope :all, order(:party_id.asc, :guest_id.asc)
	scope :by_invite_code, lambda {|i| where(:invite_code >> i)}
    
	validates :party_id, :presence => true
	validates :guest_id, :presence => true
	validates :expected_attendees, :presence => true, :numericality => { :only_integer => true, :greater_than => 0}
	validates :actual_attendees, :numericality => {:allow_nil => true, :only_integer => true, :allow_blank => true, }
	
    def invite_url
    	return "http://127.0.0.1:3000/rsvp/" + invite_code
    end
    
    private 
    
    def generate_invite_code
    	self.invite_code = SecureRandom.hex(5)
    end 
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :login_required,  :except => [:update, :rsvp, :thanks]
  # GET /invitations
  # GET /invitations.xml
  def index
    @invitations = current_host.invitations
  end

  # GET /invitations/1
  # GET /invitations/1.xml
  def show
    @invitation = Invitation.find(params[:id])
  end

  # GET /invitations/new
  # GET /invitations/new.xml
  def new
    @invitation = Invitation.new
	@parties = current_host.parties.all
	@guests = current_host.guests.all
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
	@parties = current_host.parties.all
	@guests = current_host.guests.all
  end

  # POST /invitations
  # POST /invitations.xml
  def create
    @invitation = Invitation.new(params[:invitation])
	@parties = current_host.parties.all
	@guests = current_host.guests.all 
    respond_to do |format|
      if @invitation.save
		PartyMailer.email_invitation(@invitation).deliver  
        format.html { redirect_to(@invitation, :notice => 'Invitation was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.xml
  def update
    @invitation = Invitation.find(params[:id])
	@parties = current_host.parties.all  if logged_in?
	@guests = current_host.guests.all if logged_in?
	
    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
		if !@invitation.actual_attendees.nil? && (!logged_in? || @invitation.party.host_id != current_host.id)
			format.html { redirect_to(thanks_path, :notice => 'RSVP has been successfully sent.') }
		else
			format.html { redirect_to(@invitation, :notice => 'Invitation was successfully updated.') }
		end
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.xml
  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to(invitations_url) }
    end
  end
  
  def rsvp
	@invitation = Invitation.by_invite_code(params[:invite_code]).first
  end
  
  def rsvp_create
  
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/edit.html.erb
<h1 class="horizontal">Editing invitation</h1>

<%= form_for(@invitation) do |f| %>
  <%= render :partial => "partials/errors", :locals => {:target => @invitation}  %>

  <div class="field">
    <%= f.label :party_id, 'Party: <span class="required">*</span>'.html_safe %>
    <%= f.collection_select(:party_id ,@parties,:id, :name,{:prompt =>"Select Party"})%>
  </div>
  <div class="field">
    <%= f.label :guest_id, 'Guest: <span class="required">*</span>'.html_safe %>
    <%= f.collection_select(:guest_id ,@guests,:id, :name,{:prompt =>"Select Guest"})%>
  </div>
  <div class="field">
	<%= f.label :expected_attendees, 'Expected Attendees: <span class="required">*</span>'.html_safe%>
    <%= f.text_field :expected_attendees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div class="link_actions">
<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>
</div>

app/views/invitations/index.html.erb
<% if @invitations.length > 0 %>
	<h1 class="horizontal">Your Guest Invitations</h1>

	<table class="minimal">
	  <tr>
		<th>Party</th>
		<th>Guest</th>
		<th># Expected</th>
		<th># Confirmed</th>
		<th colspan="3">Actions</th>
	  </tr>

	<% @invitations.each do |invitation| %>
	  <tr>
		<td><%= invitation.party.name %></td>
		<td><%= invitation.guest.name %></td>
		<td><%= invitation.expected_attendees %></td>
		<td><%= invitation.actual_attendees %></td>
		<td><%= link_to 'Show', invitation %></td>
		<td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
		<td><%= link_to 'Destroy', invitation, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	</table>
<% else %>
	<h2 class="horizontal">No Invitations to display</h2>
	<p>You have no invitations to display. Get started by creating a party and some guests and invite them to the party!</p>
<% end %>

<div class="link_actions">
<%= link_to 'New Invitation', new_invitation_path %>
</div>

app/views/invitations/new.html.erb
<h1 class="horizontal">New invitation</h1>

<%= form_for(@invitation) do |f| %>
  <%= render :partial => "partials/errors", :locals => {:target => @invitation}  %>

  <div class="field">
    <%= f.label :party_id, 'Party: <span class="required">*</span>'.html_safe %>
    <%= f.collection_select(:party_id ,@parties,:id, :name,{:prompt =>"Select Party"})%>
  </div>
  <div class="field">
    <%= f.label :guest_id, 'Guest: <span class="required">*</span>'.html_safe %>
    <%= f.collection_select(:guest_id ,@guests,:id, :name,{:prompt =>"Select Guest"})%>
  </div>
  <div class="field">
	<%= f.label :expected_attendees, 'Expected Attendees: <span class="required">*</span>'.html_safe %>
    <%= f.text_field :expected_attendees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div class="link_actions">
<%= link_to 'Back', invitations_path %>
</div>

app/views/invitations/rsvp.html.erb
<h1 class="horizontal">RSVP for <%= @invitation.party.name %></h1>

<%= form_for(@invitation) do |f| %>
  <%= render :partial => "partials/errors", :locals => {:target => @invitation}  %>
  <table class="rsvp">
	<tr>
		<td>
			<%= f.label "Host Name" %>
			<p><%= @invitation.party.host.name %></p>
		</td>
		<td>
			<label for="guest_name">Guest:</label>
			<p><%= @invitation.guest.name %></p>
		</td>
	<tr>
		<td>
			<%= f.label :expected_attendees %>
			<p><%= @invitation.expected_attendees %></p>
		</td>
		<td>
			<%= f.label :actual_attendees, 'Actual Attendees: <span class="required">*</span>'.html_safe %>
			<%= f.text_field :actual_attendees %>
		</td>
	</tr>
  </table>
  <div class="actions">
	<%= f.submit "RSVP"%>
  </div>
<% end %>

<%= render :partial => 'parties/party_show', :locals => {:party => @invitation.party, :show_party_name => true} %>
<% if @invitation.party.public_guestlist %>
<%= render :partial => 'parties/party_guest_list', :locals => {:invitations => @invitation.party.invitations} %>
<% end %>

app/views/invitations/show.html.erb
<h1 class="horizontal">Invitation</h1>

<p>
  <b>Party:</b>
  <%= @invitation.party.name %>
</p>

<p>
  <b>Guest:</b>
  <%= @invitation.guest.name%>
</p>

<p>
  <b>Invite url:</b>
  <%= link_to @invitation.invite_url,  @invitation.invite_url %>
</p>

<p>
  <b>Expected attendees:</b>
  <%= @invitation.expected_attendees %>
</p>

<p>
  <b>RSVP'd attendees:</b>
  <%= @invitation.actual_attendees %>
</p>

<div class="link_actions">
<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>
</div>

app/views/invitations/thanks.html.erb
<h1 class="horizontal">Thank you for RSVPing!</h1>

<%= image_tag "clapping.png", :size => "400x400", :class => "clap" %>